// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/shangsky/zerodrop/config"
	"github.com/shangsky/zerodrop/handler"
	"github.com/shangsky/zerodrop/log"
	"github.com/shangsky/zerodrop/server"
	"net/http"
)

// Injectors from wire.go:

func wireAPP(conf *config.Config) *http.Server {
	logger := log.New()
	httpHandler := handler.New(logger)
	httpServer := server.New(conf, httpHandler)
	return httpServer
}
